//! Deterministic derivation of the browser-oriented Sortformer f16 artifact.
//!
//! The public entry point authenticates the exact frozen f32 receipt and
//! package before converting anything. The resulting receipt is a derivation
//! record, not a runtime admission root: publication still requires an
//! independently frozen receipt digest plus the unchanged L2-L6 and DER gates.

#![forbid(unsafe_code)]

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

use serde::Serialize;
use sha2::{Digest, Sha256};

use crate::error::{FwError, FwResult};
use crate::native_engine::weights::SafetensorsFile;
use crate::sortformer_f16_contract::{
    SORTFORMER_F16_DERIVATION_METHOD, SORTFORMER_F16_DERIVATION_METHOD_VERSION,
    SORTFORMER_F16_DERIVATION_RECEIPT_SCHEMA, SortformerF16ArtifactDtype,
    SortformerF16DerivationIdentity, SortformerF16DerivationReceipt,
    SortformerF16PackageIdentity, SortformerF16TensorRecord, SortformerF16TensorTransform,
};
use crate::sortformer_conformance::{
    SORTFORMER_CONVERSION_RECEIPT_SHA256, VerifiedSortformerPackage,
    load_verified_sortformer_package_from_bytes,
};
#[cfg(test)]
use crate::sortformer_conformance::{
    SORTFORMER_MODEL_ID, SORTFORMER_MODEL_REVISION, SORTFORMER_PACKAGE_SHA256,
};
const PACKAGE_FORMAT: &str = "safetensors";
const BYTE_ORDER: &str = "little_endian";
const TENSOR_ORDER: &str = "lexicographic_name_order";
const METADATA_POLICY: &str = "absent";
const CONVERSION_CHUNK_ELEMENTS: usize = 16 * 1024;
const CHECKPOINT_CHUNK_BYTES: usize = 64 * 1024;
const MAX_DERIVED_HEADER_BYTES: usize = 8 * 1024 * 1024;

/// Generated bytes and their strict, canonical derivation receipt.
pub struct DerivedSortformerF16Artifact {
    package_bytes: Vec<u8>,
    receipt_bytes: Vec<u8>,
    receipt: SortformerF16DerivationReceipt,
}

impl fmt::Debug for DerivedSortformerF16Artifact {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("DerivedSortformerF16Artifact")
            .field("package_bytes", &self.package_bytes.len())
            .field("receipt_bytes", &self.receipt_bytes.len())
            .field("package_sha256", &self.receipt.package.sha256)
            .field("tensor_count", &self.receipt.package.tensor_count)
            .finish()
    }
}

impl DerivedSortformerF16Artifact {
    #[must_use]
    pub fn package_bytes(&self) -> &[u8] {
        &self.package_bytes
    }

    #[must_use]
    pub fn receipt_bytes(&self) -> &[u8] {
        &self.receipt_bytes
    }

    #[must_use]
    pub const fn receipt(&self) -> &SortformerF16DerivationReceipt {
        &self.receipt
    }

    #[must_use]
    pub fn receipt_sha256(&self) -> String {
        sha256_bytes(&self.receipt_bytes)
    }

    #[must_use]
    pub fn into_bytes(self) -> (Vec<u8>, Vec<u8>) {
        (self.package_bytes, self.receipt_bytes)
    }
}

#[derive(Debug, Clone)]
struct ParentArtifactIdentity {
    model_id: String,
    model_revision: String,
    receipt_sha256: String,
    package_sha256: String,
}

#[derive(Debug, Serialize)]
struct SafetensorsHeaderEntry<'a> {
    dtype: &'a str,
    shape: &'a [u64],
    data_offsets: [u64; 2],
}

#[derive(Default)]
struct DerivedCensus {
    f16_tensors: u64,
    f16_elements: u64,
    f16_bytes: u64,
    i64_tensors: u64,
    i64_elements: u64,
    i64_bytes: u64,
}

/// Authenticate the frozen f32 artifact and derive deterministic f16 bytes.
pub fn derive_sortformer_f16_artifact(
    parent_receipt_bytes: Vec<u8>,
    parent_package_bytes: Vec<u8>,
) -> FwResult<DerivedSortformerF16Artifact> {
    derive_sortformer_f16_artifact_with_checkpoint(
        parent_receipt_bytes,
        parent_package_bytes,
        &|| Ok(()),
    )
}

/// Cancellation-aware form of [`derive_sortformer_f16_artifact`].
pub fn derive_sortformer_f16_artifact_with_checkpoint(
    parent_receipt_bytes: Vec<u8>,
    parent_package_bytes: Vec<u8>,
    checkpoint: &(dyn Fn() -> FwResult<()> + Sync),
) -> FwResult<DerivedSortformerF16Artifact> {
    downcast_checkpoint(checkpoint)?;
    let verified = load_verified_sortformer_package_from_bytes(
        parent_receipt_bytes,
        parent_package_bytes,
        checkpoint,
    )?;
    let parent = ParentArtifactIdentity {
        model_id: verified.receipt().model.model_id.clone(),
        model_revision: verified.receipt().model.model_revision.clone(),
        receipt_sha256: SORTFORMER_CONVERSION_RECEIPT_SHA256.to_owned(),
        package_sha256: verified.receipt().package.sha256.clone(),
    };
    downcast_authenticated_package(&verified, &parent, checkpoint)
}

fn downcast_authenticated_package(
    verified: &VerifiedSortformerPackage,
    parent: &ParentArtifactIdentity,
    checkpoint: &(dyn Fn() -> FwResult<()> + Sync),
) -> FwResult<DerivedSortformerF16Artifact> {
    downcast_package(verified.safetensors(), parent, checkpoint)
}

fn downcast_package(
    source: &SafetensorsFile,
    parent: &ParentArtifactIdentity,
    checkpoint: &(dyn Fn() -> FwResult<()> + Sync),
) -> FwResult<DerivedSortformerF16Artifact> {
    downcast_checkpoint(checkpoint)?;
    if source.metadata().is_some() {
        return Err(downcast_error(
            "source_metadata",
            "authenticated source package must not contain safetensors metadata",
        ));
    }

    let payload_bytes = source_payload_upper_bound(source)?;
    let package_capacity = payload_bytes
        .checked_add(MAX_DERIVED_HEADER_BYTES + 8)
        .ok_or_else(|| downcast_error("package_bounds", "output package size overflows usize"))?;
    let mut payload = Vec::new();
    payload
        .try_reserve_exact(package_capacity)
        .map_err(|_| downcast_error("package_allocation", "output payload allocation failed"))?;
    let mut records = Vec::with_capacity(source.len());
    let mut header_records = Vec::with_capacity(source.len());
    let mut census = DerivedCensus::default();

    for name in source.names() {
        downcast_checkpoint(checkpoint)?;
        let shape = source
            .shape(name)?
            .iter()
            .copied()
            .map(|dimension| {
                u64::try_from(dimension).map_err(|_| {
                    downcast_error("source_shape", "tensor dimension does not fit u64")
                })
            })
            .collect::<FwResult<Vec<_>>>()?;
        let elements = shape.iter().try_fold(1u64, |product, &dimension| {
            product.checked_mul(dimension).ok_or_else(|| {
                downcast_error("source_shape", "tensor element count overflows u64")
            })
        })?;
        let source_raw = source.tensor_raw_bytes(name)?;
        let source_bytes = u64::try_from(source_raw.len()).map_err(|_| {
            downcast_error("source_bounds", "tensor byte count does not fit u64")
        })?;
        let begin = u64::try_from(payload.len()).map_err(|_| {
            downcast_error("package_bounds", "output offset does not fit u64")
        })?;

        let (source_dtype, destination_dtype, transform) = match source.dtype_name(name)? {
            "F32" => {
                downcast_f32_payload(name, source_raw, &mut payload, checkpoint)?;
                census.f16_tensors = checked_add(census.f16_tensors, 1, "f16 tensor count")?;
                census.f16_elements =
                    checked_add(census.f16_elements, elements, "f16 element count")?;
                census.f16_bytes = checked_add(
                    census.f16_bytes,
                    elements.checked_mul(2).ok_or_else(|| {
                        downcast_error("package_census", "f16 byte count overflows u64")
                    })?,
                    "f16 byte count",
                )?;
                (
                    SortformerF16ArtifactDtype::F32,
                    SortformerF16ArtifactDtype::F16,
                    SortformerF16TensorTransform::RoundToNearestTiesToEvenF32ToF16,
                )
            }
            "I64" => {
                for chunk in source_raw.chunks(CHECKPOINT_CHUNK_BYTES) {
                    downcast_checkpoint(checkpoint)?;
                    payload.extend_from_slice(chunk);
                }
                census.i64_tensors = checked_add(census.i64_tensors, 1, "i64 tensor count")?;
                census.i64_elements =
                    checked_add(census.i64_elements, elements, "i64 element count")?;
                census.i64_bytes =
                    checked_add(census.i64_bytes, source_bytes, "i64 byte count")?;
                (
                    SortformerF16ArtifactDtype::I64,
                    SortformerF16ArtifactDtype::I64,
                    SortformerF16TensorTransform::IdentityI64,
                )
            }
            _ => {
                return Err(downcast_error(
                    "source_dtype",
                    "source package contains a tensor that is not F32 or I64",
                ));
            }
        };

        let end = u64::try_from(payload.len()).map_err(|_| {
            downcast_error("package_bounds", "output offset does not fit u64")
        })?;
        let begin_usize = usize::try_from(begin).map_err(|_| {
            downcast_error("package_bounds", "output tensor start does not fit usize")
        })?;
        let end_usize = usize::try_from(end).map_err(|_| {
            downcast_error("package_bounds", "output tensor end does not fit usize")
        })?;
        let destination_raw = payload.get(begin_usize..end_usize).ok_or_else(|| {
            downcast_error("package_bounds", "output tensor span is unavailable")
        })?;
        records.push(SortformerF16TensorRecord {
            name: name.to_owned(),
            shape: shape.clone(),
            elements,
            source_dtype,
            destination_dtype,
            transform,
            source_bytes,
            destination_bytes: end - begin,
            source_value_sha256: sha256_bytes_with_checkpoint(source_raw, checkpoint)?,
            destination_value_sha256: sha256_bytes_with_checkpoint(destination_raw, checkpoint)?,
        });
        header_records.push((name.to_owned(), destination_dtype, shape, [begin, end]));
    }

    downcast_checkpoint(checkpoint)?;
    let package_bytes = serialize_safetensors(&header_records, payload, checkpoint)?;
    downcast_checkpoint(checkpoint)?;
    let payload_bytes = census
        .f16_bytes
        .checked_add(census.i64_bytes)
        .ok_or_else(|| downcast_error("package_census", "payload byte count overflows u64"))?;
    let package_len = u64::try_from(package_bytes.len())
        .map_err(|_| downcast_error("package_bounds", "package size does not fit u64"))?;
    let mut dtype_set = BTreeSet::new();
    if census.f16_tensors != 0 {
        dtype_set.insert(SortformerF16ArtifactDtype::F16);
    }
    if census.i64_tensors != 0 {
        dtype_set.insert(SortformerF16ArtifactDtype::I64);
    }
    let tensor_count = u64::try_from(records.len())
        .map_err(|_| downcast_error("package_census", "tensor count does not fit u64"))?;
    let package_sha256 = sha256_bytes_with_checkpoint(&package_bytes, checkpoint)?;
    downcast_checkpoint(checkpoint)?;
    let receipt = SortformerF16DerivationReceipt {
        schema_version: SORTFORMER_F16_DERIVATION_RECEIPT_SCHEMA.to_owned(),
        model_id: parent.model_id.clone(),
        model_revision: parent.model_revision.clone(),
        derivation: SortformerF16DerivationIdentity {
            parent_receipt_sha256: parent.receipt_sha256.clone(),
            parent_package_sha256: parent.package_sha256.clone(),
            method: SORTFORMER_F16_DERIVATION_METHOD.to_owned(),
            method_version: SORTFORMER_F16_DERIVATION_METHOD_VERSION.to_owned(),
            rounding_mode: "round_to_nearest_ties_to_even".to_owned(),
            receipt_contract_source_sha256: receipt_contract_source_sha256(),
            downcaster_core_source_sha256: downcaster_core_source_sha256(),
            downcaster_cli_source_sha256: downcaster_cli_source_sha256(),
            parent_verifier_source_sha256: parent_verifier_source_sha256(),
            safetensors_parser_source_sha256: safetensors_parser_source_sha256(),
            cargo_config_sha256: cargo_config_sha256(),
            cargo_manifest_sha256: cargo_manifest_sha256(),
            cargo_lock_sha256: cargo_lock_sha256(),
            rust_toolchain_sha256: rust_toolchain_sha256(),
        },
        package: SortformerF16PackageIdentity {
            format: PACKAGE_FORMAT.to_owned(),
            sha256: package_sha256,
            bytes: package_len,
            payload_bytes,
            tensor_count,
            f16_tensors: census.f16_tensors,
            f16_elements: census.f16_elements,
            f16_bytes: census.f16_bytes,
            i64_tensors: census.i64_tensors,
            i64_elements: census.i64_elements,
            i64_bytes: census.i64_bytes,
            dtype_set: dtype_set.into_iter().collect(),
            byte_order: BYTE_ORDER.to_owned(),
            tensor_order: TENSOR_ORDER.to_owned(),
            metadata_policy: METADATA_POLICY.to_owned(),
        },
        records,
    };
    downcast_checkpoint(checkpoint)?;
    let receipt_bytes = canonical_json_bytes(&receipt)?;
    downcast_checkpoint(checkpoint)?;
    Ok(DerivedSortformerF16Artifact {
        package_bytes,
        receipt_bytes,
        receipt,
    })
}

fn source_payload_upper_bound(source: &SafetensorsFile) -> FwResult<usize> {
    source.names().try_fold(0usize, |total, name| {
        let raw_len = source.tensor_raw_bytes(name)?.len();
        let output_len = match source.dtype_name(name)? {
            "F32" => raw_len / 2,
            "I64" => raw_len,
            _ => {
                return Err(downcast_error(
                    "source_dtype",
                    "source package contains a tensor that is not F32 or I64",
                ));
            }
        };
        total.checked_add(output_len).ok_or_else(|| {
            downcast_error("package_bounds", "output payload size overflows usize")
        })
    })
}

fn downcast_f32_payload(
    name: &str,
    source: &[u8],
    output: &mut Vec<u8>,
    checkpoint: &(dyn Fn() -> FwResult<()> + Sync),
) -> FwResult<()> {
    if !source.len().is_multiple_of(4) {
        return Err(downcast_error(
            "source_bounds",
            "F32 tensor payload is not a multiple of four bytes",
        ));
    }
    for chunk in source.chunks(CONVERSION_CHUNK_ELEMENTS * 4) {
        downcast_checkpoint(checkpoint)?;
        for bytes in chunk.as_chunks::<4>().0 {
            let bits = f32_to_f16_rne_bits(f32::from_le_bytes(*bytes)).map_err(|_| {
                downcast_error(
                    "nonfinite_source",
                    &format!("tensor `{name}` contains a non-finite or f16-overflowing value"),
                )
            })?;
            output.extend_from_slice(&bits.to_le_bytes());
        }
    }
    Ok(())
}

fn serialize_safetensors(
    records: &[(String, SortformerF16ArtifactDtype, Vec<u64>, [u64; 2])],
    mut payload: Vec<u8>,
    checkpoint: &(dyn Fn() -> FwResult<()> + Sync),
) -> FwResult<Vec<u8>> {
    let mut header = BTreeMap::new();
    for (name, dtype, shape, offsets) in records {
        let dtype = match dtype {
            SortformerF16ArtifactDtype::F16 => "F16",
            SortformerF16ArtifactDtype::I64 => "I64",
            SortformerF16ArtifactDtype::F32 => {
                return Err(downcast_error(
                    "package_dtype",
                    "derived package unexpectedly retained F32 storage",
                ));
            }
        };
        header.insert(
            name.as_str(),
            SafetensorsHeaderEntry {
                dtype,
                shape,
                data_offsets: *offsets,
            },
        );
    }
    downcast_checkpoint(checkpoint)?;
    let mut header_bytes = serde_json::to_vec(&header)?;
    header_bytes.resize(header_bytes.len().next_multiple_of(8), b' ');
    let header_len = u64::try_from(header_bytes.len())
        .map_err(|_| downcast_error("package_bounds", "header size does not fit u64"))?;
    if header_bytes.len() > MAX_DERIVED_HEADER_BYTES {
        return Err(downcast_error(
            "package_bounds",
            "derived safetensors header exceeds its bounded envelope",
        ));
    }
    downcast_checkpoint(checkpoint)?;
    let prefix_len = 8usize
        .checked_add(header_bytes.len())
        .ok_or_else(|| downcast_error("package_bounds", "package prefix overflows usize"))?;
    let payload_len = payload.len();
    payload.resize(
        payload_len
            .checked_add(prefix_len)
            .ok_or_else(|| downcast_error("package_bounds", "package size overflows usize"))?,
        0,
    );
    let mut end = payload_len;
    while end != 0 {
        downcast_checkpoint(checkpoint)?;
        let start = end.saturating_sub(CHECKPOINT_CHUNK_BYTES);
        payload.copy_within(start..end, start + prefix_len);
        end = start;
    }
    payload[..8].copy_from_slice(&header_len.to_le_bytes());
    payload[8..prefix_len].copy_from_slice(&header_bytes);
    downcast_checkpoint(checkpoint)?;
    Ok(payload)
}

fn f32_to_f16_rne_bits(value: f32) -> Result<u16, ()> {
    let bits = value.to_bits();
    let sign = ((bits >> 16) & 0x8000) as u16;
    let exponent = ((bits >> 23) & 0xff) as i32;
    let mantissa = bits & 0x7f_ffff;
    if exponent == 0xff {
        return Err(());
    }
    if exponent == 0 {
        return Ok(sign);
    }
    let unbiased = exponent - 127;
    if unbiased > 15 {
        return Err(());
    }
    if unbiased >= -14 {
        let mut half_exponent = (unbiased + 15) as u16;
        let retained = mantissa >> 13;
        let remainder = mantissa & 0x1fff;
        let rounded = retained
            + u32::from(remainder > 0x1000 || (remainder == 0x1000 && retained & 1 != 0));
        let half_mantissa = if rounded == 0x400 {
            half_exponent += 1;
            0
        } else {
            rounded as u16
        };
        if half_exponent >= 0x1f {
            return Err(());
        }
        return Ok(sign | (half_exponent << 10) | half_mantissa);
    }

    let shift = u32::try_from(-unbiased - 1).map_err(|_| ())?;
    if shift > 24 {
        return Ok(sign);
    }
    let significand = mantissa | 0x80_0000;
    let retained = significand >> shift;
    let remainder_mask = (1u32 << shift) - 1;
    let remainder = significand & remainder_mask;
    let halfway = 1u32 << (shift - 1);
    let rounded = retained
        + u32::from(remainder > halfway || (remainder == halfway && retained & 1 != 0));
    Ok(sign | rounded as u16)
}

fn checked_add(left: u64, right: u64, label: &str) -> FwResult<u64> {
    left.checked_add(right).ok_or_else(|| {
        downcast_error(
            "package_census",
            &format!("derived {label} overflows u64"),
        )
    })
}

fn downcast_checkpoint(checkpoint: &(dyn Fn() -> FwResult<()> + Sync)) -> FwResult<()> {
    match checkpoint() {
        Ok(()) => Ok(()),
        Err(FwError::Cancelled(_)) => Err(FwError::Cancelled(
            "sortformer_f16_downcast.cancelled: cooperative checkpoint requested cancellation"
                .to_owned(),
        )),
        Err(_) => Err(FwError::ContractViolation(
            "sortformer_f16_downcast.checkpoint_failure: checkpoint returned a \
             non-cancellation failure"
                .to_owned(),
        )),
    }
}

fn downcaster_core_source_sha256() -> String {
    sha256_bytes(include_bytes!("sortformer_f16_downcast.rs"))
}

fn receipt_contract_source_sha256() -> String {
    sha256_bytes(include_bytes!("sortformer_f16_contract.rs"))
}

fn downcaster_cli_source_sha256() -> String {
    sha256_bytes(include_bytes!("bin/sortformer_f16_downcast.rs"))
}

fn parent_verifier_source_sha256() -> String {
    sha256_bytes(include_bytes!("sortformer_conformance.rs"))
}

fn safetensors_parser_source_sha256() -> String {
    sha256_bytes(include_bytes!("native_engine/weights.rs"))
}

fn cargo_config_sha256() -> String {
    sha256_bytes(include_bytes!("../.cargo/config.toml"))
}

fn cargo_manifest_sha256() -> String {
    sha256_bytes(include_bytes!("../Cargo.toml"))
}

fn cargo_lock_sha256() -> String {
    sha256_bytes(include_bytes!("../Cargo.lock"))
}

fn rust_toolchain_sha256() -> String {
    sha256_bytes(include_bytes!("../rust-toolchain.toml"))
}

fn sha256_bytes(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("{:x}", hasher.finalize())
}

fn sha256_bytes_with_checkpoint(
    bytes: &[u8],
    checkpoint: &(dyn Fn() -> FwResult<()> + Sync),
) -> FwResult<String> {
    let mut hasher = Sha256::new();
    for chunk in bytes.chunks(CHECKPOINT_CHUNK_BYTES) {
        downcast_checkpoint(checkpoint)?;
        hasher.update(chunk);
    }
    downcast_checkpoint(checkpoint)?;
    Ok(format!("{:x}", hasher.finalize()))
}

fn canonical_json_bytes<T: Serialize>(value: &T) -> FwResult<Vec<u8>> {
    let value = serde_json::to_value(value)?;
    let mut output = Vec::new();
    write_lexicographic_json(&value, &mut output)?;
    Ok(output)
}

fn write_lexicographic_json(value: &serde_json::Value, output: &mut Vec<u8>) -> FwResult<()> {
    match value {
        serde_json::Value::Null
        | serde_json::Value::Bool(_)
        | serde_json::Value::Number(_)
        | serde_json::Value::String(_) => serde_json::to_writer(output, value)?,
        serde_json::Value::Array(values) => {
            output.push(b'[');
            for (index, item) in values.iter().enumerate() {
                if index != 0 {
                    output.push(b',');
                }
                write_lexicographic_json(item, output)?;
            }
            output.push(b']');
        }
        serde_json::Value::Object(values) => {
            output.push(b'{');
            let mut keys = values.keys().collect::<Vec<_>>();
            keys.sort_unstable();
            for (index, key) in keys.into_iter().enumerate() {
                if index != 0 {
                    output.push(b',');
                }
                serde_json::to_writer(&mut *output, key)?;
                output.push(b':');
                write_lexicographic_json(&values[key], output)?;
            }
            output.push(b'}');
        }
    }
    Ok(())
}

fn downcast_error(code: &str, message: &str) -> FwError {
    FwError::InvalidRequest(format!("sortformer_f16_downcast.{code}: {message}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ft_core::Float16;

    fn synthetic_parent() -> ParentArtifactIdentity {
        ParentArtifactIdentity {
            model_id: SORTFORMER_MODEL_ID.to_owned(),
            model_revision: SORTFORMER_MODEL_REVISION.to_owned(),
            receipt_sha256: SORTFORMER_CONVERSION_RECEIPT_SHA256.to_owned(),
            package_sha256: SORTFORMER_PACKAGE_SHA256.to_owned(),
        }
    }

    fn synthetic_package(entries: &[(&str, &str, &[u64], Vec<u8>)]) -> SafetensorsFile {
        let mut offset = 0u64;
        let mut header = serde_json::Map::new();
        let mut payload = Vec::new();
        let mut sorted = entries.to_vec();
        sorted.sort_unstable_by_key(|entry| entry.0);
        for (name, dtype, shape, raw) in sorted {
            let end = offset + u64::try_from(raw.len()).expect("fixture bytes fit u64");
            header.insert(
                name.to_owned(),
                serde_json::json!({
                    "dtype": dtype,
                    "shape": shape,
                    "data_offsets": [offset, end],
                }),
            );
            payload.extend_from_slice(&raw);
            offset = end;
        }
        let mut header_bytes = serde_json::to_vec(&header).expect("serialize fixture header");
        header_bytes.resize(header_bytes.len().next_multiple_of(8), b' ');
        let mut bytes = Vec::new();
        bytes.extend_from_slice(
            &u64::try_from(header_bytes.len())
                .expect("fixture header fits u64")
                .to_le_bytes(),
        );
        bytes.extend_from_slice(&header_bytes);
        bytes.extend_from_slice(&payload);
        SafetensorsFile::from_owned_bytes(bytes).expect("parse synthetic package")
    }

    fn f32_bytes(values: &[f32]) -> Vec<u8> {
        values
            .iter()
            .flat_map(|value| value.to_le_bytes())
            .collect()
    }

    #[test]
    fn rne_halfway_cases_choose_even_destination() {
        let cases = [
            (1.000_488_3, 0x3c00),
            (1.001_464_8, 0x3c02),
            (-1.000_488_3, 0xbc00),
            (-1.001_464_8, 0xbc02),
        ];
        for (value, expected) in cases {
            assert_eq!(f32_to_f16_rne_bits(value), Ok(expected));
        }
    }

    #[test]
    fn rne_matches_half_oracle_around_every_positive_finite_midpoint() {
        for lower_bits in 0u16..0x7bff {
            let lower = Float16::from_bits(lower_bits).to_f32();
            let upper = Float16::from_bits(lower_bits + 1).to_f32();
            let midpoint = (lower + upper) * 0.5;
            let probes = [
                f32::from_bits(midpoint.to_bits().saturating_sub(1)),
                midpoint,
                f32::from_bits(midpoint.to_bits().saturating_add(1)),
            ];
            for probe in probes {
                assert_eq!(
                    f32_to_f16_rne_bits(probe),
                    Ok(Float16::from_f32(probe).to_bits()),
                    "lower f16 bits {lower_bits:#06x}, probe {probe:?}"
                );
                assert_eq!(
                    f32_to_f16_rne_bits(-probe),
                    Ok(Float16::from_f32(-probe).to_bits()),
                    "negative lower f16 bits {lower_bits:#06x}, probe {:?}",
                    -probe
                );
            }
        }
    }

    #[test]
    fn rne_preserves_boundaries_and_rejects_nonfinite_or_overflow() {
        assert_eq!(f32_to_f16_rne_bits(0.0), Ok(0x0000));
        assert_eq!(f32_to_f16_rne_bits(-0.0), Ok(0x8000));
        assert_eq!(f32_to_f16_rne_bits(2.0f32.powi(-24)), Ok(0x0001));
        assert_eq!(f32_to_f16_rne_bits(2.0f32.powi(-25)), Ok(0x0000));
        assert_eq!(f32_to_f16_rne_bits(65_504.0), Ok(0x7bff));
        assert!(f32_to_f16_rne_bits(65_520.0).is_err());
        assert!(f32_to_f16_rne_bits(f32::INFINITY).is_err());
        assert!(f32_to_f16_rne_bits(f32::NEG_INFINITY).is_err());
        assert!(f32_to_f16_rne_bits(f32::NAN).is_err());
    }

    #[test]
    fn derivation_is_deterministic_and_preserves_i64_exactly() {
        let f32_payload = f32_bytes(&[1.000_488_3, -0.0, 2.0f32.powi(-24)]);
        let i64_payload = [7i64, -9i64]
            .into_iter()
            .flat_map(i64::to_le_bytes)
            .collect::<Vec<_>>();
        let source = synthetic_package(&[
            ("z.control", "I64", &[2], i64_payload.clone()),
            ("a.weight", "F32", &[3], f32_payload),
        ]);
        let first = downcast_package(&source, &synthetic_parent(), &|| Ok(()))
            .expect("first derivation");
        let second = downcast_package(&source, &synthetic_parent(), &|| Ok(()))
            .expect("second derivation");
        assert_eq!(first.package_bytes(), second.package_bytes());
        assert_eq!(first.receipt_bytes(), second.receipt_bytes());

        let derived = SafetensorsFile::from_bytes(first.package_bytes()).expect("derived package");
        assert_eq!(derived.names().collect::<Vec<_>>(), ["a.weight", "z.control"]);
        assert_eq!(derived.dtype_name("a.weight").expect("weight dtype"), "F16");
        assert_eq!(derived.dtype_name("z.control").expect("control dtype"), "I64");
        assert_eq!(
            derived.tensor_raw_bytes("a.weight").expect("weight payload"),
            [0x00, 0x3c, 0x00, 0x80, 0x01, 0x00]
        );
        assert_eq!(
            derived.tensor_raw_bytes("z.control").expect("control payload"),
            i64_payload
        );
        assert_eq!(first.receipt().package.f16_tensors, 1);
        assert_eq!(first.receipt().package.f16_elements, 3);
        assert_eq!(first.receipt().package.i64_tensors, 1);
        assert_eq!(first.receipt().package.i64_elements, 2);
        assert_eq!(
            first.receipt().package.sha256,
            sha256_bytes(first.package_bytes())
        );
    }

    #[test]
    fn source_mutation_changes_package_and_bound_record_digests() {
        let first_source = synthetic_package(&[("weight", "F32", &[1], f32_bytes(&[1.0]))]);
        let second_source = synthetic_package(&[(
            "weight",
            "F32",
            &[1],
            f32_bytes(&[f32::from_bits(1.0f32.to_bits() + 8_192)]),
        )]);
        let first = downcast_package(&first_source, &synthetic_parent(), &|| Ok(()))
            .expect("first derivation");
        let second = downcast_package(&second_source, &synthetic_parent(), &|| Ok(()))
            .expect("mutated derivation");
        assert_ne!(first.package_bytes(), second.package_bytes());
        assert_ne!(first.receipt_bytes(), second.receipt_bytes());
        assert_ne!(
            first.receipt().records[0].source_value_sha256,
            second.receipt().records[0].source_value_sha256
        );
        assert_ne!(
            first.receipt().records[0].destination_value_sha256,
            second.receipt().records[0].destination_value_sha256
        );
    }

    #[test]
    fn cancellation_between_payload_chunks_returns_no_artifact() {
        use std::sync::atomic::{AtomicUsize, Ordering};

        let values = vec![1.0; CONVERSION_CHUNK_ELEMENTS + 1];
        let source = synthetic_package(&[(
            "weight",
            "F32",
            &[u64::try_from(values.len()).expect("fixture length fits u64")],
            f32_bytes(&values),
        )]);
        let calls = AtomicUsize::new(0);
        let error = downcast_package(&source, &synthetic_parent(), &|| {
            if calls.fetch_add(1, Ordering::SeqCst) >= 3 {
                Err(FwError::Cancelled("synthetic stop".to_owned()))
            } else {
                Ok(())
            }
        })
        .expect_err("second payload chunk must observe cancellation");
        assert!(matches!(error, FwError::Cancelled(_)));
        assert_eq!(calls.load(Ordering::SeqCst), 4);
    }

    #[test]
    fn checkpoint_hash_observes_every_chunk_and_the_terminal_boundary() {
        use std::sync::atomic::{AtomicUsize, Ordering};

        let bytes = vec![0x5a; CHECKPOINT_CHUNK_BYTES + 1];
        let successful_calls = AtomicUsize::new(0);
        let digest = sha256_bytes_with_checkpoint(&bytes, &|| {
            successful_calls.fetch_add(1, Ordering::SeqCst);
            Ok(())
        })
        .expect("hash with checkpoints");
        assert_eq!(digest, sha256_bytes(&bytes));
        assert_eq!(successful_calls.load(Ordering::SeqCst), 3);

        for cancel_at in 0..3 {
            let calls = AtomicUsize::new(0);
            let error = sha256_bytes_with_checkpoint(&bytes, &|| {
                if calls.fetch_add(1, Ordering::SeqCst) == cancel_at {
                    Err(FwError::Cancelled("synthetic stop".to_owned()))
                } else {
                    Ok(())
                }
            })
            .expect_err("each hash checkpoint must be cancellation-observable");
            assert!(matches!(error, FwError::Cancelled(_)));
            assert_eq!(calls.load(Ordering::SeqCst), cancel_at + 1);
        }

        let calls = AtomicUsize::new(0);
        let error = sha256_bytes_with_checkpoint(&[], &|| {
            calls.fetch_add(1, Ordering::SeqCst);
            Err(FwError::Cancelled("synthetic empty-input stop".to_owned()))
        })
        .expect_err("empty input must still observe the terminal checkpoint");
        assert!(matches!(error, FwError::Cancelled(_)));
        assert_eq!(calls.load(Ordering::SeqCst), 1);
    }

    #[test]
    fn chunked_serialization_preserves_payload_and_observes_relocation_cancellation() {
        use std::sync::atomic::{AtomicUsize, Ordering};

        let payload_len = CHECKPOINT_CHUNK_BYTES * 2 + 16;
        let payload = (0..payload_len)
            .map(|index| u8::try_from(index % 251).expect("fixture byte fits u8"))
            .collect::<Vec<_>>();
        let records = vec![(
            "control".to_owned(),
            SortformerF16ArtifactDtype::I64,
            vec![u64::try_from(payload_len / 8).expect("fixture shape fits u64")],
            [0, u64::try_from(payload_len).expect("fixture length fits u64")],
        )];
        let calls = AtomicUsize::new(0);
        let package = serialize_safetensors(&records, payload.clone(), &|| {
            calls.fetch_add(1, Ordering::SeqCst);
            Ok(())
        })
        .expect("serialize chunked payload");
        let header_len = usize::try_from(u64::from_le_bytes(
            package[..8].try_into().expect("header prefix is eight bytes"),
        ))
        .expect("header length fits usize");
        assert_eq!(&package[8 + header_len..], payload.as_slice());
        assert_eq!(calls.load(Ordering::SeqCst), 6);

        for cancel_at in 2..6 {
            let calls = AtomicUsize::new(0);
            let error = serialize_safetensors(&records, payload.clone(), &|| {
                if calls.fetch_add(1, Ordering::SeqCst) == cancel_at {
                    Err(FwError::Cancelled("synthetic relocation stop".to_owned()))
                } else {
                    Ok(())
                }
            })
            .expect_err("relocation and terminal checkpoints must observe cancellation");
            assert!(matches!(error, FwError::Cancelled(_)));
            assert_eq!(calls.load(Ordering::SeqCst), cancel_at + 1);
        }
    }

    #[test]
    fn tail_cancellation_never_returns_an_artifact() {
        use std::sync::atomic::{AtomicUsize, Ordering};

        let source = synthetic_package(&[("weight", "F32", &[1], f32_bytes(&[1.0]))]);
        let successful_calls = AtomicUsize::new(0);
        downcast_package(&source, &synthetic_parent(), &|| {
            successful_calls.fetch_add(1, Ordering::SeqCst);
            Ok(())
        })
        .expect("uncancelled derivation");
        assert_eq!(successful_calls.load(Ordering::SeqCst), 18);

        for cancel_at in 7..18 {
            let calls = AtomicUsize::new(0);
            let error = downcast_package(&source, &synthetic_parent(), &|| {
                if calls.fetch_add(1, Ordering::SeqCst) == cancel_at {
                    Err(FwError::Cancelled("synthetic tail stop".to_owned()))
                } else {
                    Ok(())
                }
            })
            .expect_err("tail cancellation must prevent artifact return");
            assert!(matches!(error, FwError::Cancelled(_)));
            assert_eq!(calls.load(Ordering::SeqCst), cancel_at + 1);
        }
    }

    #[test]
    fn unsupported_or_nonfinite_source_fails_before_artifact_emission() {
        let nonfinite = synthetic_package(&[(
            "weight",
            "F32",
            &[2],
            f32_bytes(&[1.0, f32::INFINITY]),
        )]);
        let error = downcast_package(&nonfinite, &synthetic_parent(), &|| Ok(()))
            .expect_err("nonfinite source must fail");
        assert!(error.to_string().contains("nonfinite_source"));

        let already_half = synthetic_package(&[(
            "weight",
            "F16",
            &[1],
            1.0f32.to_bits().to_le_bytes()[..2].to_vec(),
        )]);
        let error = downcast_package(&already_half, &synthetic_parent(), &|| Ok(()))
            .expect_err("non-F32 source must fail");
        assert!(error.to_string().contains("source_dtype"));
    }
}
