//! Deterministic derivation of the browser-oriented Sortformer f16 artifact.
//!
//! The public entry point authenticates the exact frozen f32 receipt and
//! package before converting anything. The resulting receipt is a derivation
//! record, not a runtime admission root: publication still requires an
//! independently frozen receipt digest plus the unchanged L2-L6 and DER gates.

#![forbid(unsafe_code)]

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::error::{FwError, FwResult};
use crate::native_engine::weights::SafetensorsFile;
use crate::sortformer_conformance::{
    SORTFORMER_CONVERSION_RECEIPT_SHA256, SORTFORMER_MODEL_ID, SORTFORMER_MODEL_REVISION,
    SORTFORMER_PACKAGE_SHA256, VerifiedSortformerPackage,
    load_verified_sortformer_package_from_bytes,
};

pub const SORTFORMER_F16_DERIVATION_RECEIPT_SCHEMA: &str =
    "franken-whisper-sortformer-f16-derivation-receipt-v2";
pub const SORTFORMER_F16_DERIVATION_METHOD: &str = "rte-f16-downcast";
pub const SORTFORMER_F16_DERIVATION_METHOD_VERSION: &str = "1";
const PACKAGE_FORMAT: &str = "safetensors";
const BYTE_ORDER: &str = "little_endian";
const TENSOR_ORDER: &str = "lexicographic_name_order";
const METADATA_POLICY: &str = "absent";
const CONVERSION_CHUNK_ELEMENTS: usize = 16 * 1024;

/// Strict receipt for one deterministic f32-to-f16 derivation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SortformerF16DerivationReceipt {
    pub schema_version: String,
    pub model_id: String,
    pub model_revision: String,
    pub derivation: SortformerF16DerivationIdentity,
    pub package: SortformerF16PackageIdentity,
    pub records: Vec<SortformerF16TensorRecord>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SortformerF16DerivationIdentity {
    pub parent_receipt_sha256: String,
    pub parent_package_sha256: String,
    pub method: String,
    pub method_version: String,
    pub rounding_mode: String,
    pub downcaster_source_sha256: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SortformerF16PackageIdentity {
    pub format: String,
    pub sha256: String,
    pub bytes: u64,
    pub payload_bytes: u64,
    pub tensor_count: u64,
    pub f16_tensors: u64,
    pub f16_elements: u64,
    pub f16_bytes: u64,
    pub i64_tensors: u64,
    pub i64_elements: u64,
    pub i64_bytes: u64,
    pub dtype_set: Vec<SortformerF16ArtifactDtype>,
    pub byte_order: String,
    pub tensor_order: String,
    pub metadata_policy: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum SortformerF16ArtifactDtype {
    #[serde(rename = "F32")]
    F32,
    #[serde(rename = "F16")]
    F16,
    #[serde(rename = "I64")]
    I64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SortformerF16TensorTransform {
    RoundToNearestTiesToEvenF32ToF16,
    IdentityI64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SortformerF16TensorRecord {
    pub name: String,
    pub shape: Vec<u64>,
    pub elements: u64,
    pub source_dtype: SortformerF16ArtifactDtype,
    pub destination_dtype: SortformerF16ArtifactDtype,
    pub transform: SortformerF16TensorTransform,
    pub source_bytes: u64,
    pub destination_bytes: u64,
    pub source_value_sha256: String,
    pub destination_value_sha256: String,
}

/// Generated bytes and their strict, canonical derivation receipt.
pub struct DerivedSortformerF16Artifact {
    package_bytes: Vec<u8>,
    receipt_bytes: Vec<u8>,
    receipt: SortformerF16DerivationReceipt,
}

impl fmt::Debug for DerivedSortformerF16Artifact {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("DerivedSortformerF16Artifact")
            .field("package_bytes", &self.package_bytes.len())
            .field("receipt_bytes", &self.receipt_bytes.len())
            .field("package_sha256", &self.receipt.package.sha256)
            .field("tensor_count", &self.receipt.package.tensor_count)
            .finish()
    }
}

impl DerivedSortformerF16Artifact {
    #[must_use]
    pub fn package_bytes(&self) -> &[u8] {
        &self.package_bytes
    }

    #[must_use]
    pub fn receipt_bytes(&self) -> &[u8] {
        &self.receipt_bytes
    }

    #[must_use]
    pub const fn receipt(&self) -> &SortformerF16DerivationReceipt {
        &self.receipt
    }

    #[must_use]
    pub fn receipt_sha256(&self) -> String {
        sha256_bytes(&self.receipt_bytes)
    }

    #[must_use]
    pub fn into_bytes(self) -> (Vec<u8>, Vec<u8>) {
        (self.package_bytes, self.receipt_bytes)
    }
}

#[derive(Debug, Clone)]
struct ParentArtifactIdentity {
    model_id: String,
    model_revision: String,
    receipt_sha256: String,
    package_sha256: String,
}

#[derive(Debug, Serialize)]
struct SafetensorsHeaderEntry<'a> {
    dtype: &'a str,
    shape: &'a [u64],
    data_offsets: [u64; 2],
}

#[derive(Default)]
struct DerivedCensus {
    f16_tensors: u64,
    f16_elements: u64,
    f16_bytes: u64,
    i64_tensors: u64,
    i64_elements: u64,
    i64_bytes: u64,
}

/// Authenticate the frozen f32 artifact and derive deterministic f16 bytes.
pub fn derive_sortformer_f16_artifact(
    parent_receipt_bytes: Vec<u8>,
    parent_package_bytes: Vec<u8>,
) -> FwResult<DerivedSortformerF16Artifact> {
    derive_sortformer_f16_artifact_with_checkpoint(
        parent_receipt_bytes,
        parent_package_bytes,
        &|| Ok(()),
    )
}

/// Cancellation-aware form of [`derive_sortformer_f16_artifact`].
pub fn derive_sortformer_f16_artifact_with_checkpoint(
    parent_receipt_bytes: Vec<u8>,
    parent_package_bytes: Vec<u8>,
    checkpoint: &(dyn Fn() -> FwResult<()> + Sync),
) -> FwResult<DerivedSortformerF16Artifact> {
    checkpoint()?;
    let verified = load_verified_sortformer_package_from_bytes(
        parent_receipt_bytes,
        parent_package_bytes,
        checkpoint,
    )?;
    let parent = ParentArtifactIdentity {
        model_id: verified.receipt().model.model_id.clone(),
        model_revision: verified.receipt().model.model_revision.clone(),
        receipt_sha256: SORTFORMER_CONVERSION_RECEIPT_SHA256.to_owned(),
        package_sha256: verified.receipt().package.sha256.clone(),
    };
    downcast_authenticated_package(&verified, &parent, checkpoint)
}

fn downcast_authenticated_package(
    verified: &VerifiedSortformerPackage,
    parent: &ParentArtifactIdentity,
    checkpoint: &(dyn Fn() -> FwResult<()> + Sync),
) -> FwResult<DerivedSortformerF16Artifact> {
    downcast_package(verified.safetensors(), parent, checkpoint)
}

fn downcast_package(
    source: &SafetensorsFile,
    parent: &ParentArtifactIdentity,
    checkpoint: &(dyn Fn() -> FwResult<()> + Sync),
) -> FwResult<DerivedSortformerF16Artifact> {
    checkpoint()?;
    if source.metadata().is_some() {
        return Err(downcast_error(
            "source_metadata",
            "authenticated source package must not contain safetensors metadata",
        ));
    }

    let mut payload = Vec::new();
    payload
        .try_reserve(source_payload_upper_bound(source)?)
        .map_err(|_| downcast_error("package_allocation", "output payload allocation failed"))?;
    let mut records = Vec::with_capacity(source.len());
    let mut header_records = Vec::with_capacity(source.len());
    let mut census = DerivedCensus::default();

    for name in source.names() {
        checkpoint()?;
        let shape = source
            .shape(name)?
            .iter()
            .copied()
            .map(|dimension| {
                u64::try_from(dimension).map_err(|_| {
                    downcast_error("source_shape", "tensor dimension does not fit u64")
                })
            })
            .collect::<FwResult<Vec<_>>>()?;
        let elements = shape.iter().try_fold(1u64, |product, &dimension| {
            product.checked_mul(dimension).ok_or_else(|| {
                downcast_error("source_shape", "tensor element count overflows u64")
            })
        })?;
        let source_raw = source.tensor_raw_bytes(name)?;
        let source_bytes = u64::try_from(source_raw.len()).map_err(|_| {
            downcast_error("source_bounds", "tensor byte count does not fit u64")
        })?;
        let begin = u64::try_from(payload.len()).map_err(|_| {
            downcast_error("package_bounds", "output offset does not fit u64")
        })?;

        let (source_dtype, destination_dtype, transform) = match source.dtype_name(name)? {
            "F32" => {
                downcast_f32_payload(name, source_raw, &mut payload, checkpoint)?;
                census.f16_tensors = checked_add(census.f16_tensors, 1, "f16 tensor count")?;
                census.f16_elements =
                    checked_add(census.f16_elements, elements, "f16 element count")?;
                census.f16_bytes = checked_add(
                    census.f16_bytes,
                    elements.checked_mul(2).ok_or_else(|| {
                        downcast_error("package_census", "f16 byte count overflows u64")
                    })?,
                    "f16 byte count",
                )?;
                (
                    SortformerF16ArtifactDtype::F32,
                    SortformerF16ArtifactDtype::F16,
                    SortformerF16TensorTransform::RoundToNearestTiesToEvenF32ToF16,
                )
            }
            "I64" => {
                payload.extend_from_slice(source_raw);
                census.i64_tensors = checked_add(census.i64_tensors, 1, "i64 tensor count")?;
                census.i64_elements =
                    checked_add(census.i64_elements, elements, "i64 element count")?;
                census.i64_bytes =
                    checked_add(census.i64_bytes, source_bytes, "i64 byte count")?;
                (
                    SortformerF16ArtifactDtype::I64,
                    SortformerF16ArtifactDtype::I64,
                    SortformerF16TensorTransform::IdentityI64,
                )
            }
            _ => {
                return Err(downcast_error(
                    "source_dtype",
                    "source package contains a tensor that is not F32 or I64",
                ));
            }
        };

        let end = u64::try_from(payload.len()).map_err(|_| {
            downcast_error("package_bounds", "output offset does not fit u64")
        })?;
        let begin_usize = usize::try_from(begin).map_err(|_| {
            downcast_error("package_bounds", "output tensor start does not fit usize")
        })?;
        let end_usize = usize::try_from(end).map_err(|_| {
            downcast_error("package_bounds", "output tensor end does not fit usize")
        })?;
        let destination_raw = payload.get(begin_usize..end_usize).ok_or_else(|| {
            downcast_error("package_bounds", "output tensor span is unavailable")
        })?;
        records.push(SortformerF16TensorRecord {
            name: name.to_owned(),
            shape: shape.clone(),
            elements,
            source_dtype,
            destination_dtype,
            transform,
            source_bytes,
            destination_bytes: end - begin,
            source_value_sha256: sha256_bytes(source_raw),
            destination_value_sha256: sha256_bytes(destination_raw),
        });
        header_records.push((name.to_owned(), destination_dtype, shape, [begin, end]));
    }

    let package_bytes = serialize_safetensors(&header_records, payload)?;
    let payload_bytes = census
        .f16_bytes
        .checked_add(census.i64_bytes)
        .ok_or_else(|| downcast_error("package_census", "payload byte count overflows u64"))?;
    let package_len = u64::try_from(package_bytes.len())
        .map_err(|_| downcast_error("package_bounds", "package size does not fit u64"))?;
    let mut dtype_set = BTreeSet::new();
    if census.f16_tensors != 0 {
        dtype_set.insert(SortformerF16ArtifactDtype::F16);
    }
    if census.i64_tensors != 0 {
        dtype_set.insert(SortformerF16ArtifactDtype::I64);
    }
    let tensor_count = u64::try_from(records.len())
        .map_err(|_| downcast_error("package_census", "tensor count does not fit u64"))?;
    let receipt = SortformerF16DerivationReceipt {
        schema_version: SORTFORMER_F16_DERIVATION_RECEIPT_SCHEMA.to_owned(),
        model_id: parent.model_id.clone(),
        model_revision: parent.model_revision.clone(),
        derivation: SortformerF16DerivationIdentity {
            parent_receipt_sha256: parent.receipt_sha256.clone(),
            parent_package_sha256: parent.package_sha256.clone(),
            method: SORTFORMER_F16_DERIVATION_METHOD.to_owned(),
            method_version: SORTFORMER_F16_DERIVATION_METHOD_VERSION.to_owned(),
            rounding_mode: "round_to_nearest_ties_to_even".to_owned(),
            downcaster_source_sha256: downcaster_source_sha256(),
        },
        package: SortformerF16PackageIdentity {
            format: PACKAGE_FORMAT.to_owned(),
            sha256: sha256_bytes(&package_bytes),
            bytes: package_len,
            payload_bytes,
            tensor_count,
            f16_tensors: census.f16_tensors,
            f16_elements: census.f16_elements,
            f16_bytes: census.f16_bytes,
            i64_tensors: census.i64_tensors,
            i64_elements: census.i64_elements,
            i64_bytes: census.i64_bytes,
            dtype_set: dtype_set.into_iter().collect(),
            byte_order: BYTE_ORDER.to_owned(),
            tensor_order: TENSOR_ORDER.to_owned(),
            metadata_policy: METADATA_POLICY.to_owned(),
        },
        records,
    };
    let receipt_bytes = canonical_json_bytes(&receipt)?;
    Ok(DerivedSortformerF16Artifact {
        package_bytes,
        receipt_bytes,
        receipt,
    })
}

/// Validate derivation consistency against the current downcaster source.
///
/// This is deliberately not runtime artifact admission. A published f16 lane
/// must additionally pin the independently reviewed receipt digest.
pub fn validate_derived_sortformer_f16_artifact(
    receipt_bytes: &[u8],
    package_bytes: &[u8],
) -> FwResult<SortformerF16DerivationReceipt> {
    let receipt: SortformerF16DerivationReceipt = serde_json::from_slice(receipt_bytes)
        .map_err(|_| downcast_error("receipt_schema", "receipt is not strict v2 JSON"))?;
    if canonical_json_bytes(&receipt)? != receipt_bytes {
        return Err(downcast_error(
            "receipt_canonical",
            "receipt bytes are not canonical JSON",
        ));
    }
    if receipt.schema_version != SORTFORMER_F16_DERIVATION_RECEIPT_SCHEMA
        || receipt.model_id != SORTFORMER_MODEL_ID
        || receipt.model_revision != SORTFORMER_MODEL_REVISION
        || receipt.derivation.parent_receipt_sha256 != SORTFORMER_CONVERSION_RECEIPT_SHA256
        || receipt.derivation.parent_package_sha256 != SORTFORMER_PACKAGE_SHA256
        || receipt.derivation.method != SORTFORMER_F16_DERIVATION_METHOD
        || receipt.derivation.method_version != SORTFORMER_F16_DERIVATION_METHOD_VERSION
        || receipt.derivation.rounding_mode != "round_to_nearest_ties_to_even"
        || receipt.derivation.downcaster_source_sha256 != downcaster_source_sha256()
    {
        return Err(downcast_error(
            "derivation_identity",
            "receipt does not bind the frozen parent and current derivation method",
        ));
    }
    let package_len = u64::try_from(package_bytes.len())
        .map_err(|_| downcast_error("package_identity", "package size does not fit u64"))?;
    if receipt.package.format != PACKAGE_FORMAT
        || receipt.package.byte_order != BYTE_ORDER
        || receipt.package.tensor_order != TENSOR_ORDER
        || receipt.package.metadata_policy != METADATA_POLICY
        || receipt.package.bytes != package_len
        || receipt.package.sha256 != sha256_bytes(package_bytes)
    {
        return Err(downcast_error(
            "package_identity",
            "derived package identity does not match the receipt",
        ));
    }
    verify_compact_package_layout(package_bytes, receipt.package.payload_bytes)?;
    let package = SafetensorsFile::from_bytes(package_bytes)
        .map_err(|_| downcast_error("package_structure", "derived package is not safetensors"))?;
    if package.metadata().is_some() || package.len() != receipt.records.len() {
        return Err(downcast_error(
            "package_census",
            "derived package metadata or tensor count changed",
        ));
    }
    verify_derived_records(&receipt, &package)?;
    Ok(receipt)
}

fn verify_derived_records(
    receipt: &SortformerF16DerivationReceipt,
    package: &SafetensorsFile,
) -> FwResult<()> {
    let mut f16_tensors = 0u64;
    let mut f16_elements = 0u64;
    let mut f16_bytes = 0u64;
    let mut i64_tensors = 0u64;
    let mut i64_elements = 0u64;
    let mut i64_bytes = 0u64;
    for (record, name) in receipt.records.iter().zip(package.names()) {
        let expected_shape = record
            .shape
            .iter()
            .map(|&dimension| {
                usize::try_from(dimension).map_err(|_| {
                    downcast_error("tensor_identity", "tensor dimension does not fit usize")
                })
            })
            .collect::<FwResult<Vec<_>>>()?;
        if record.name != name
            || package.shape(name)? != expected_shape.as_slice()
            || record.destination_value_sha256 != sha256_bytes(package.tensor_raw_bytes(name)?)
        {
            return Err(downcast_error(
                "tensor_identity",
                "derived tensor name, shape, or payload digest changed",
            ));
        }
        let raw_bytes = u64::try_from(package.tensor_raw_bytes(name)?.len()).map_err(|_| {
            downcast_error("package_census", "tensor byte count does not fit u64")
        })?;
        if record.destination_bytes != raw_bytes {
            return Err(downcast_error(
                "tensor_census",
                "derived tensor byte count changed",
            ));
        }
        match (
            record.source_dtype,
            record.destination_dtype,
            record.transform,
            package.dtype_name(name)?,
        ) {
            (
                SortformerF16ArtifactDtype::F32,
                SortformerF16ArtifactDtype::F16,
                SortformerF16TensorTransform::RoundToNearestTiesToEvenF32ToF16,
                "F16",
            ) => {
                let expected_source_bytes = record.elements.checked_mul(4).ok_or_else(|| {
                    downcast_error("tensor_census", "F32 source byte count overflows u64")
                })?;
                let expected_destination_bytes = record.elements.checked_mul(2).ok_or_else(|| {
                    downcast_error("tensor_census", "F16 destination byte count overflows u64")
                })?;
                if record.source_bytes != expected_source_bytes
                    || record.destination_bytes != expected_destination_bytes
                {
                    return Err(downcast_error(
                        "tensor_census",
                        "F32-to-F16 tensor byte census changed",
                    ));
                }
                f16_tensors = checked_add(f16_tensors, 1, "f16 tensor count")?;
                f16_elements = checked_add(f16_elements, record.elements, "f16 elements")?;
                f16_bytes = checked_add(f16_bytes, raw_bytes, "f16 bytes")?;
            }
            (
                SortformerF16ArtifactDtype::I64,
                SortformerF16ArtifactDtype::I64,
                SortformerF16TensorTransform::IdentityI64,
                "I64",
            ) => {
                let expected_bytes = record.elements.checked_mul(8).ok_or_else(|| {
                    downcast_error("tensor_census", "I64 tensor byte count overflows u64")
                })?;
                if record.source_bytes != expected_bytes
                    || record.destination_bytes != expected_bytes
                    || record.source_value_sha256 != record.destination_value_sha256
                {
                    return Err(downcast_error(
                        "control_identity",
                        "I64 control tensor was not copied byte-for-byte",
                    ));
                }
                i64_tensors = checked_add(i64_tensors, 1, "i64 tensor count")?;
                i64_elements = checked_add(i64_elements, record.elements, "i64 elements")?;
                i64_bytes = checked_add(i64_bytes, raw_bytes, "i64 bytes")?;
            }
            _ => {
                return Err(downcast_error(
                    "tensor_dtype",
                    "derived tensor dtype or transform changed",
                ));
            }
        }
    }
    let expected_dtype_set = [
        (f16_tensors != 0).then_some(SortformerF16ArtifactDtype::F16),
        (i64_tensors != 0).then_some(SortformerF16ArtifactDtype::I64),
    ]
    .into_iter()
    .flatten()
    .collect::<Vec<_>>();
    let record_count = u64::try_from(receipt.records.len())
        .map_err(|_| downcast_error("package_census", "record count does not fit u64"))?;
    let payload_bytes = f16_bytes
        .checked_add(i64_bytes)
        .ok_or_else(|| downcast_error("package_census", "payload byte count overflows u64"))?;
    if receipt.package.tensor_count != record_count
        || receipt.package.f16_tensors != f16_tensors
        || receipt.package.f16_elements != f16_elements
        || receipt.package.f16_bytes != f16_bytes
        || receipt.package.i64_tensors != i64_tensors
        || receipt.package.i64_elements != i64_elements
        || receipt.package.i64_bytes != i64_bytes
        || receipt.package.payload_bytes != payload_bytes
        || receipt.package.dtype_set != expected_dtype_set
    {
        return Err(downcast_error(
            "package_census",
            "derived package dtype census changed",
        ));
    }
    Ok(())
}

fn verify_compact_package_layout(bytes: &[u8], expected_payload_bytes: u64) -> FwResult<()> {
    let prefix: [u8; 8] = bytes
        .get(..8)
        .and_then(|value| value.try_into().ok())
        .ok_or_else(|| {
            downcast_error(
                "package_structure",
                "derived package lacks a complete header-length prefix",
            )
        })?;
    let header_len = usize::try_from(u64::from_le_bytes(prefix)).map_err(|_| {
        downcast_error(
            "package_structure",
            "derived package header length does not fit usize",
        )
    })?;
    let data_start = 8usize.checked_add(header_len).ok_or_else(|| {
        downcast_error(
            "package_structure",
            "derived package header offset overflows usize",
        )
    })?;
    let data_len = bytes.len().checked_sub(data_start).ok_or_else(|| {
        downcast_error(
            "package_structure",
            "derived package header extends past the package",
        )
    })?;
    if u64::try_from(data_len).ok() != Some(expected_payload_bytes) {
        return Err(downcast_error(
            "package_layout",
            "derived package payload size changed",
        ));
    }
    let header: serde_json::Value = serde_json::from_slice(
        bytes
            .get(8..data_start)
            .ok_or_else(|| downcast_error("package_structure", "header span is unavailable"))?,
    )
    .map_err(|_| downcast_error("package_structure", "header is not valid JSON"))?;
    let entries = header.as_object().ok_or_else(|| {
        downcast_error("package_structure", "safetensors header is not an object")
    })?;
    let mut spans = Vec::with_capacity(entries.len());
    for (name, entry) in entries {
        if name == "__metadata__" {
            return Err(downcast_error(
                "package_layout",
                "derived package must not contain metadata",
            ));
        }
        let offsets = entry
            .get("data_offsets")
            .and_then(serde_json::Value::as_array)
            .filter(|values| values.len() == 2)
            .ok_or_else(|| {
                downcast_error("package_structure", "tensor offsets are not a pair")
            })?;
        let begin = offsets[0]
            .as_u64()
            .ok_or_else(|| downcast_error("package_structure", "tensor start is not u64"))?;
        let end = offsets[1]
            .as_u64()
            .ok_or_else(|| downcast_error("package_structure", "tensor end is not u64"))?;
        spans.push((name.as_str(), begin, end));
    }
    spans.sort_unstable_by_key(|(name, _, _)| *name);
    let mut cursor = 0u64;
    for (_, begin, end) in spans {
        if begin != cursor || end < begin || end > expected_payload_bytes {
            return Err(downcast_error(
                "package_layout",
                "derived tensor spans are not compact and non-overlapping",
            ));
        }
        cursor = end;
    }
    if cursor != expected_payload_bytes {
        return Err(downcast_error(
            "package_layout",
            "derived tensor spans do not cover the complete payload",
        ));
    }
    Ok(())
}

fn source_payload_upper_bound(source: &SafetensorsFile) -> FwResult<usize> {
    source.names().try_fold(0usize, |total, name| {
        let raw_len = source.tensor_raw_bytes(name)?.len();
        let output_len = match source.dtype_name(name)? {
            "F32" => raw_len / 2,
            "I64" => raw_len,
            _ => {
                return Err(downcast_error(
                    "source_dtype",
                    "source package contains a tensor that is not F32 or I64",
                ));
            }
        };
        total.checked_add(output_len).ok_or_else(|| {
            downcast_error("package_bounds", "output payload size overflows usize")
        })
    })
}

fn downcast_f32_payload(
    name: &str,
    source: &[u8],
    output: &mut Vec<u8>,
    checkpoint: &(dyn Fn() -> FwResult<()> + Sync),
) -> FwResult<()> {
    if !source.len().is_multiple_of(4) {
        return Err(downcast_error(
            "source_bounds",
            "F32 tensor payload is not a multiple of four bytes",
        ));
    }
    for chunk in source.chunks(CONVERSION_CHUNK_ELEMENTS * 4) {
        checkpoint()?;
        for bytes in chunk.as_chunks::<4>().0 {
            let bits = f32_to_f16_rne_bits(f32::from_le_bytes(*bytes)).map_err(|_| {
                downcast_error(
                    "nonfinite_source",
                    &format!("tensor `{name}` contains a non-finite or f16-overflowing value"),
                )
            })?;
            output.extend_from_slice(&bits.to_le_bytes());
        }
    }
    Ok(())
}

fn serialize_safetensors(
    records: &[(String, SortformerF16ArtifactDtype, Vec<u64>, [u64; 2])],
    payload: Vec<u8>,
) -> FwResult<Vec<u8>> {
    let mut header = BTreeMap::new();
    for (name, dtype, shape, offsets) in records {
        let dtype = match dtype {
            SortformerF16ArtifactDtype::F16 => "F16",
            SortformerF16ArtifactDtype::I64 => "I64",
            SortformerF16ArtifactDtype::F32 => {
                return Err(downcast_error(
                    "package_dtype",
                    "derived package unexpectedly retained F32 storage",
                ));
            }
        };
        header.insert(
            name.as_str(),
            SafetensorsHeaderEntry {
                dtype,
                shape,
                data_offsets: *offsets,
            },
        );
    }
    let mut header_bytes = serde_json::to_vec(&header)?;
    header_bytes.resize(header_bytes.len().next_multiple_of(8), b' ');
    let header_len = u64::try_from(header_bytes.len())
        .map_err(|_| downcast_error("package_bounds", "header size does not fit u64"))?;
    let total_len = 8usize
        .checked_add(header_bytes.len())
        .and_then(|length| length.checked_add(payload.len()))
        .ok_or_else(|| downcast_error("package_bounds", "package size overflows usize"))?;
    let mut package = Vec::new();
    package
        .try_reserve_exact(total_len)
        .map_err(|_| downcast_error("package_allocation", "output package allocation failed"))?;
    package.extend_from_slice(&header_len.to_le_bytes());
    package.extend_from_slice(&header_bytes);
    package.extend_from_slice(&payload);
    Ok(package)
}

fn f32_to_f16_rne_bits(value: f32) -> Result<u16, ()> {
    let bits = value.to_bits();
    let sign = ((bits >> 16) & 0x8000) as u16;
    let exponent = ((bits >> 23) & 0xff) as i32;
    let mantissa = bits & 0x7f_ffff;
    if exponent == 0xff {
        return Err(());
    }
    if exponent == 0 {
        return Ok(sign);
    }
    let unbiased = exponent - 127;
    if unbiased > 15 {
        return Err(());
    }
    if unbiased >= -14 {
        let mut half_exponent = (unbiased + 15) as u16;
        let retained = mantissa >> 13;
        let remainder = mantissa & 0x1fff;
        let rounded = retained
            + u32::from(remainder > 0x1000 || (remainder == 0x1000 && retained & 1 != 0));
        let half_mantissa = if rounded == 0x400 {
            half_exponent += 1;
            0
        } else {
            rounded as u16
        };
        if half_exponent >= 0x1f {
            return Err(());
        }
        return Ok(sign | (half_exponent << 10) | half_mantissa);
    }

    let shift = u32::try_from(-unbiased - 1).map_err(|_| ())?;
    if shift > 24 {
        return Ok(sign);
    }
    let significand = mantissa | 0x80_0000;
    let retained = significand >> shift;
    let remainder_mask = (1u32 << shift) - 1;
    let remainder = significand & remainder_mask;
    let halfway = 1u32 << (shift - 1);
    let rounded = retained
        + u32::from(remainder > halfway || (remainder == halfway && retained & 1 != 0));
    Ok(sign | rounded as u16)
}

fn checked_add(left: u64, right: u64, label: &str) -> FwResult<u64> {
    left.checked_add(right).ok_or_else(|| {
        downcast_error(
            "package_census",
            &format!("derived {label} overflows u64"),
        )
    })
}

fn downcaster_source_sha256() -> String {
    sha256_bytes(include_bytes!("sortformer_f16_downcast.rs"))
}

fn sha256_bytes(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("{:x}", hasher.finalize())
}

fn canonical_json_bytes<T: Serialize>(value: &T) -> FwResult<Vec<u8>> {
    let value = serde_json::to_value(value)?;
    let mut output = Vec::new();
    write_lexicographic_json(&value, &mut output)?;
    Ok(output)
}

fn write_lexicographic_json(value: &serde_json::Value, output: &mut Vec<u8>) -> FwResult<()> {
    match value {
        serde_json::Value::Null
        | serde_json::Value::Bool(_)
        | serde_json::Value::Number(_)
        | serde_json::Value::String(_) => serde_json::to_writer(output, value)?,
        serde_json::Value::Array(values) => {
            output.push(b'[');
            for (index, item) in values.iter().enumerate() {
                if index != 0 {
                    output.push(b',');
                }
                write_lexicographic_json(item, output)?;
            }
            output.push(b']');
        }
        serde_json::Value::Object(values) => {
            output.push(b'{');
            let mut keys = values.keys().collect::<Vec<_>>();
            keys.sort_unstable();
            for (index, key) in keys.into_iter().enumerate() {
                if index != 0 {
                    output.push(b',');
                }
                serde_json::to_writer(&mut *output, key)?;
                output.push(b':');
                write_lexicographic_json(&values[key], output)?;
            }
            output.push(b'}');
        }
    }
    Ok(())
}

fn downcast_error(code: &str, message: &str) -> FwError {
    FwError::InvalidRequest(format!("sortformer_f16_downcast.{code}: {message}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ft_core::Float16;

    fn synthetic_parent() -> ParentArtifactIdentity {
        ParentArtifactIdentity {
            model_id: SORTFORMER_MODEL_ID.to_owned(),
            model_revision: SORTFORMER_MODEL_REVISION.to_owned(),
            receipt_sha256: SORTFORMER_CONVERSION_RECEIPT_SHA256.to_owned(),
            package_sha256: SORTFORMER_PACKAGE_SHA256.to_owned(),
        }
    }

    fn synthetic_package(entries: &[(&str, &str, &[u64], Vec<u8>)]) -> SafetensorsFile {
        let mut offset = 0u64;
        let mut header = serde_json::Map::new();
        let mut payload = Vec::new();
        let mut sorted = entries.to_vec();
        sorted.sort_unstable_by_key(|entry| entry.0);
        for (name, dtype, shape, raw) in sorted {
            let end = offset + u64::try_from(raw.len()).expect("fixture bytes fit u64");
            header.insert(
                name.to_owned(),
                serde_json::json!({
                    "dtype": dtype,
                    "shape": shape,
                    "data_offsets": [offset, end],
                }),
            );
            payload.extend_from_slice(&raw);
            offset = end;
        }
        let mut header_bytes = serde_json::to_vec(&header).expect("serialize fixture header");
        header_bytes.resize(header_bytes.len().next_multiple_of(8), b' ');
        let mut bytes = Vec::new();
        bytes.extend_from_slice(
            &u64::try_from(header_bytes.len())
                .expect("fixture header fits u64")
                .to_le_bytes(),
        );
        bytes.extend_from_slice(&header_bytes);
        bytes.extend_from_slice(&payload);
        SafetensorsFile::from_owned_bytes(bytes).expect("parse synthetic package")
    }

    fn f32_bytes(values: &[f32]) -> Vec<u8> {
        values
            .iter()
            .flat_map(|value| value.to_le_bytes())
            .collect()
    }

    #[test]
    fn rne_halfway_cases_choose_even_destination() {
        let cases = [
            (1.000_488_281_25, 0x3c00),
            (1.001_464_843_75, 0x3c02),
            (-1.000_488_281_25, 0xbc00),
            (-1.001_464_843_75, 0xbc02),
        ];
        for (value, expected) in cases {
            assert_eq!(f32_to_f16_rne_bits(value), Ok(expected));
        }
    }

    #[test]
    fn rne_matches_half_oracle_around_every_positive_finite_midpoint() {
        for lower_bits in 0u16..0x7bff {
            let lower = Float16::from_bits(lower_bits).to_f32();
            let upper = Float16::from_bits(lower_bits + 1).to_f32();
            let midpoint = (lower + upper) * 0.5;
            let probes = [
                f32::from_bits(midpoint.to_bits().saturating_sub(1)),
                midpoint,
                f32::from_bits(midpoint.to_bits().saturating_add(1)),
            ];
            for probe in probes {
                assert_eq!(
                    f32_to_f16_rne_bits(probe),
                    Ok(Float16::from_f32(probe).to_bits()),
                    "lower f16 bits {lower_bits:#06x}, probe {probe:?}"
                );
                assert_eq!(
                    f32_to_f16_rne_bits(-probe),
                    Ok(Float16::from_f32(-probe).to_bits()),
                    "negative lower f16 bits {lower_bits:#06x}, probe {:?}",
                    -probe
                );
            }
        }
    }

    #[test]
    fn rne_preserves_boundaries_and_rejects_nonfinite_or_overflow() {
        assert_eq!(f32_to_f16_rne_bits(0.0), Ok(0x0000));
        assert_eq!(f32_to_f16_rne_bits(-0.0), Ok(0x8000));
        assert_eq!(f32_to_f16_rne_bits(2.0f32.powi(-24)), Ok(0x0001));
        assert_eq!(f32_to_f16_rne_bits(2.0f32.powi(-25)), Ok(0x0000));
        assert_eq!(f32_to_f16_rne_bits(65_504.0), Ok(0x7bff));
        assert!(f32_to_f16_rne_bits(65_520.0).is_err());
        assert!(f32_to_f16_rne_bits(f32::INFINITY).is_err());
        assert!(f32_to_f16_rne_bits(f32::NEG_INFINITY).is_err());
        assert!(f32_to_f16_rne_bits(f32::NAN).is_err());
    }

    #[test]
    fn derivation_is_deterministic_and_preserves_i64_exactly() {
        let f32_payload = f32_bytes(&[1.000_488_281_25, -0.0, 2.0f32.powi(-24)]);
        let i64_payload = [7i64, -9i64]
            .into_iter()
            .flat_map(i64::to_le_bytes)
            .collect::<Vec<_>>();
        let source = synthetic_package(&[
            ("z.control", "I64", &[2], i64_payload.clone()),
            ("a.weight", "F32", &[3], f32_payload),
        ]);
        let first = downcast_package(&source, &synthetic_parent(), &|| Ok(()))
            .expect("first derivation");
        let second = downcast_package(&source, &synthetic_parent(), &|| Ok(()))
            .expect("second derivation");
        assert_eq!(first.package_bytes(), second.package_bytes());
        assert_eq!(first.receipt_bytes(), second.receipt_bytes());

        let derived = SafetensorsFile::from_bytes(first.package_bytes()).expect("derived package");
        assert_eq!(derived.names().collect::<Vec<_>>(), ["a.weight", "z.control"]);
        assert_eq!(derived.dtype_name("a.weight").expect("weight dtype"), "F16");
        assert_eq!(derived.dtype_name("z.control").expect("control dtype"), "I64");
        assert_eq!(
            derived.tensor_raw_bytes("a.weight").expect("weight payload"),
            [0x00, 0x3c, 0x00, 0x80, 0x01, 0x00]
        );
        assert_eq!(
            derived.tensor_raw_bytes("z.control").expect("control payload"),
            i64_payload
        );
        assert_eq!(first.receipt().package.f16_tensors, 1);
        assert_eq!(first.receipt().package.f16_elements, 3);
        assert_eq!(first.receipt().package.i64_tensors, 1);
        assert_eq!(first.receipt().package.i64_elements, 2);
    }

    #[test]
    fn consistency_validator_rejects_receipt_and_package_mutations() {
        let source = synthetic_package(&[("weight", "F32", &[1], f32_bytes(&[1.0]))]);
        let artifact = downcast_package(&source, &synthetic_parent(), &|| Ok(()))
            .expect("derive fixture");

        let mut package = artifact.package_bytes().to_vec();
        *package.last_mut().expect("payload byte") ^= 1;
        let error = validate_derived_sortformer_f16_artifact(artifact.receipt_bytes(), &package)
            .expect_err("package mutation must fail");
        assert!(error.to_string().contains("package_identity"));

        let mut receipt: serde_json::Value =
            serde_json::from_slice(artifact.receipt_bytes()).expect("receipt JSON");
        receipt["derivation"]["method"] = serde_json::json!("toward-zero");
        let receipt = canonical_json_bytes(&receipt).expect("mutated canonical receipt");
        let error = validate_derived_sortformer_f16_artifact(&receipt, artifact.package_bytes())
            .expect_err("method mutation must fail");
        assert!(error.to_string().contains("derivation_identity"));
    }

    #[test]
    fn unsupported_or_nonfinite_source_fails_before_artifact_emission() {
        let nonfinite = synthetic_package(&[(
            "weight",
            "F32",
            &[2],
            f32_bytes(&[1.0, f32::INFINITY]),
        )]);
        let error = downcast_package(&nonfinite, &synthetic_parent(), &|| Ok(()))
            .expect_err("nonfinite source must fail");
        assert!(error.to_string().contains("nonfinite_source"));

        let already_half = synthetic_package(&[(
            "weight",
            "F16",
            &[1],
            1.0f32.to_bits().to_le_bytes()[..2].to_vec(),
        )]);
        let error = downcast_package(&already_half, &synthetic_parent(), &|| Ok(()))
            .expect_err("non-F32 source must fail");
        assert!(error.to_string().contains("source_dtype"));
    }
}
